Repository prgrms-be-devcourse/NBE5-7-2-Team09, pull requests merged in 2025-05, with the labels that each got.

#9 Feat/exception/3
  Readio/src/main/java/ninegle/Readio/global/exception/BusinessException.java
  Readio/src/main/java/ninegle/Readio/global/exception/domain/ErrorCode.java
  Readio/src/main/java/ninegle/Readio/global/exception/dto/ErrorResponse.java
  Readio/src/main/java/ninegle/Readio/global/exception/handler/GlobalExceptionHandler.java
Labels: feature, BE

#19 feat: 관리자 페이지 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/admin/AdminProtectedRoute.tsx
  frontend/src/components/ui/calendar.tsx
  frontend/src/components/ui/popover.tsx
  frontend/src/components/ui/table.tsx
  frontend/src/contexts/AdminAuthContext.tsx
  frontend/src/interface/Admin.tsx
  frontend/src/pages/admin/AdminDashboard.tsx
  frontend/src/pages/admin/AdminLoginPage.tsx
  frontend/src/utils/api/adminAuthService.ts
Labels: feature, FE

#21 Feat/change book add input/20
  frontend/src/pages/admin/AdminDashboard.tsx
Labels: feature, FE

#33 feat: 리뷰 조회, 등록 API 연동
  Readio/src/main/java/ninegle/Readio/admin/config/SecurityConfig.java
  Readio/src/main/java/ninegle/Readio/book/controller/BookController.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/review/ReviewFilters.tsx
  frontend/src/components/review/ReviewForm.tsx
  frontend/src/components/review/ReviewList.tsx
  frontend/src/pages/book/BookDetailPage.tsx
  frontend/src/pages/book/BookReviewsPage.tsx
  frontend/src/pages/member/MyPage.tsx
  frontend/src/utils/api/reviewService.ts
Labels: feature, FE

#46 feat: 리뷰 수정, 삭제 API 연동 및 toast를 sonner로 변경
  frontend/src/App.tsx
  frontend/src/components/book/CategoryRedirect.tsx
  frontend/src/components/layout/NavBar.tsx
  frontend/src/components/review/ReviewCard.tsx
  frontend/src/components/review/ReviewList.tsx
  frontend/src/components/ui/skeleton.tsx
  frontend/src/contexts/AuthContext.tsx
  frontend/src/interface/AuthContextType.tsx
  frontend/src/interface/SignupForm.tsx
  frontend/src/pages/book/BookDetailPage.tsx
  frontend/src/pages/book/BookReviewsPage.tsx
  frontend/src/pages/book/BooksPage.tsx
  frontend/src/pages/library/LibraryDetailPage.tsx
  frontend/src/pages/library/LibraryPage.tsx
  frontend/src/pages/member/LoginPage.tsx
  frontend/src/pages/member/SignupPage.tsx
  frontend/src/pages/member/WishlistPage.tsx
  frontend/src/types/book.ts
  frontend/src/utils/api/authService.ts
  frontend/src/utils/api/bookService.ts
  frontend/src/utils/api/reviewService.ts
  frontend/src/utils/validation/CheckoutValidation.tsx
Labels: feature, FE

#48 feat: 마이페이지 API 연동
  frontend/src/pages/member/MyPage.tsx
  frontend/src/types/user.ts
  frontend/src/utils/api/userService.ts
Labels: feature, FE

#53 feat: 라이브러리 api 연동
  Readio/src/main/java/ninegle/Readio/library/domain/Library.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ui/radio-group.tsx
  frontend/src/pages/book/BookDetailPage.tsx
  frontend/src/pages/library/LibraryDetailPage.tsx
  frontend/src/pages/library/LibraryPage.tsx
  frontend/src/utils/api/bookService.ts
  frontend/src/utils/api/libraryService.ts
Labels: feature, FE

#54 fix: Library 테이블 명 수정
  Readio/src/main/java/ninegle/Readio/library/domain/Library.java
Labels: fix, BE

#56 fix: 핸드폰 번호 데이터 전송 수정
  frontend/src/interface/FormErrors.tsx
  frontend/src/interface/SignupForm.tsx
  frontend/src/pages/member/SignupPage.tsx
Labels: fix, FE

#58 feat: 관심 도서 api 연동
  frontend/src/App.tsx
  frontend/src/components/book/BookCover.tsx
  frontend/src/components/layout/NavBar.tsx
  frontend/src/pages/book/BookDetailPage.tsx
  frontend/src/pages/library/LibraryDetailPage.tsx
  frontend/src/pages/member/PreferencePage.tsx
  frontend/src/pages/member/WishlistPage.tsx
  frontend/src/utils/api/bookService.ts
  frontend/src/utils/api/libraryService.ts
  frontend/src/utils/api/preferenceService.ts
  frontend/src/utils/api/wishlistService.ts
Labels: feature, FE

#63 design: 불필요한 ui 제거 및 변경
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/book/BooksPage.tsx
  frontend/src/pages/member/LoginPage.tsx
  frontend/src/pages/member/SignupPage.tsx
Labels: FE

#65 design: 로고 추가 및 사이트 색상값 변경
  frontend/src/assets/ReadioLogo.png
  frontend/src/components/layout/NavBar.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/book/BookDetailPage.tsx
  frontend/src/pages/book/BooksPage.tsx
  frontend/src/pages/library/LibraryPage.tsx
  frontend/src/pages/member/LoginPage.tsx
  frontend/src/pages/member/SignupPage.tsx
Labels: FE

#66 [Feat] 메일서비스구현(구독결제, 취소, 회원가입)
  .idea/libraries/Gradle__org_eclipse_angus_jakarta_mail_2_0_3.xml
  .idea/libraries/Gradle__org_springframework_boot_spring_boot_starter_mail_3_4_4.xml
  .idea/libraries/Gradle__org_springframework_spring_context_support_6_2_5.xml
  .idea/modules/Readio.main.iml
  .idea/modules/Readio.test.iml
  Readio/build.gradle
  Readio/src/main/java/ninegle/Readio/global/config/ApplicationConfig.java
  Readio/src/main/java/ninegle/Readio/mail/subscription/service/SubscriptionMailSender.java
  Readio/src/main/java/ninegle/Readio/mail/subscription/service/SubscriptionMailTemplateProvider.java
  Readio/src/main/java/ninegle/Readio/mail/user/service/UserMailSender.java
  Readio/src/main/java/ninegle/Readio/mail/user/service/UserMailTemplateProvider.java
  Readio/src/main/java/ninegle/Readio/subscription/service/SubscriptionManager.java
  Readio/src/main/java/ninegle/Readio/user/service/UserService.java
Labels: feature, BE

#70 [feat] 구독만료 안내 이메일 구현
  Readio/src/main/java/ninegle/Readio/ReadioApplication.java
  Readio/src/main/java/ninegle/Readio/global/config/ApplicationConfig.java
  Readio/src/main/java/ninegle/Readio/mail/subscription/scheduler/SubscriptionReminderScheduler.java
  Readio/src/main/java/ninegle/Readio/mail/subscription/service/SubscriptionMailSender.java
  Readio/src/main/java/ninegle/Readio/mail/subscription/service/SubscriptionMailTemplateProvider.java
Labels: feature, BE

#75 feat: 책 관련 API 연동
  frontend/src/components/layout/NavBar.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/book/BooksPage.tsx
  frontend/src/pages/book/EpubReaderPage.tsx
  frontend/src/utils/api/bookService.ts
  frontend/src/utils/api/categoryService.ts
Labels: feature, FE

#88 feat: 관리자 API 연동
  frontend/src/components/layout/NavBar.tsx
  frontend/src/pages/admin/AdminDashboard.tsx
  frontend/src/types/publisher.ts
  frontend/src/utils/api/publisherService.ts
Labels: feature, FE

#94 design: 토스페이 ui 개선
  frontend/src/components/ui/PointChargeModal.tsx
  frontend/src/pages/admin/AdminDashboard.tsx
  frontend/src/pages/member/MyPage.tsx
  frontend/src/pages/payment/CheckoutPage.tsx
  frontend/src/pages/payment/SuccessPage.tsx
Labels: FE

#96 feat: 책 읽기 API 연동
  frontend/src/App.tsx
  frontend/src/pages/admin/AdminDashboard.tsx
  frontend/src/pages/book/EpubReaderPage.tsx
Labels: feature, FE

#105 [Feat] cs관련 프론트페이지 추가
  frontend/src/App.tsx
  frontend/src/components/cs/faq.tsx
  frontend/src/components/cs/notice.tsx
  frontend/src/components/layout/Footer.tsx
Labels: feature, FE

#114 [refactor] 뷰어페이지 전면 수정
  frontend/src/pages/book/EpubReaderPage.tsx
Labels: feature, refactor, FE

#126 refactor : 마이페이지, 구독, 메일서비스
  Readio/src/main/java/ninegle/Readio/global/unit/BaseResponse.java
  Readio/src/main/java/ninegle/Readio/mail/subscription/scheduler/SubscriptionReminderScheduler.java
  Readio/src/main/java/ninegle/Readio/mail/subscription/service/SubscriptionMailSender.java
  Readio/src/main/java/ninegle/Readio/mail/subscription/service/SubscriptionMailTemplateProvider.java
  Readio/src/main/java/ninegle/Readio/mail/user/service/UserMailSender.java
  Readio/src/main/java/ninegle/Readio/mail/user/service/UserMailTemplateProvider.java
  Readio/src/main/java/ninegle/Readio/mypage/controller/MyPageUserController.java
  Readio/src/main/java/ninegle/Readio/mypage/controller/PointController.java
  Readio/src/main/java/ninegle/Readio/mypage/dto/response/PointResponseDto.java
  Readio/src/main/java/ninegle/Readio/mypage/dto/response/UserInfoDto.java
  Readio/src/main/java/ninegle/Readio/mypage/mapper/MyPageUserMapper.java
  Readio/src/main/java/ninegle/Readio/mypage/mapper/PointMapper.java
  Readio/src/main/java/ninegle/Readio/mypage/service/MyPageUserService.java
  Readio/src/main/java/ninegle/Readio/mypage/service/PointService.java
  Readio/src/main/java/ninegle/Readio/subscription/controller/SubscriptionController.java
  Readio/src/main/java/ninegle/Readio/subscription/domain/Subscription.java
  Readio/src/main/java/ninegle/Readio/subscription/dto/response/SubscriptionResponseDto.java
  Readio/src/main/java/ninegle/Readio/subscription/mapper/SubscriptionMapper.java
  Readio/src/main/java/ninegle/Readio/subscription/repository/SubscriptionRepository.java
  Readio/src/main/java/ninegle/Readio/subscription/service/SubscriptionManager.java
  Readio/src/main/java/ninegle/Readio/subscription/service/SubscriptionService.java
Labels: refactor, BE
